version: 0.2

phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
      - GITHUB_REPO_URL=https://github.com/teuteuguy/gg-sense-hat-imu
      - AWS_REGION=us-west-2
      - echo Getting the Instance ID of our SSM managed device
      - INSTANCE_ID=`aws ssm describe-instance-information --region $AWS_REGION --query 'InstanceInformationList[?Name==\`donkeycar\`].InstanceId' --output text`
      - echo InstanceId = $INSTANCE_ID
      - echo Getting the AWS IoT Get Credentials endpoint
      - IOT_CREDENTIAL_ENDPOINT=`aws iot describe-endpoint --endpoint-type iot:CredentialProvider --region $AWS_REGION`
      - echo AWS IoT Endpoint = $IOT_CREDENTIAL_ENDPOINT
  build:
    commands:
      - echo Running the build on the SSM managed device
      - aws ssm send-command --region $AWS_REGION --instance-ids "$INSTANCE_ID" --document-name "rpi-build" --parameters gitRepositoryURL="$GITHUB_REPO_URL",iotCredentialEndpoint="$IOT_CREDENTIAL_ENDPOINT"
